language: php

services:
  - mysql

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

install:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - nvm install 4.4
  - composer self-update

script:
  - make build      --no-print-directory
  - cat ./resources/cck-joomla/configuration.php
  - make server-cms --no-print-directory
  - make test-all   --no-print-directory

after_success:
  - make coveralls  --no-print-directory
