language: php

services:
  - mysql

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

install:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - nvm install 4.4

script:
  - make build      --no-print-directory
  - php ./scripts/prepare-joomla-config.php
  - make server-cms --no-print-directory
  - make test-all   --no-print-directory

after_success:
  - make coveralls  --no-print-directory
