language: php

services:
  - mysql

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - '7.1.0alpha1'
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.1.0alpha1'
    - php: 7.0
    - php: hhvm
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

install:
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;
  - nvm install 4.4
  - composer self-update

script:
  - make build      --no-print-directory
  - make server-cms --no-print-directory
  - make test-all   --no-print-directory

after_success:
  - make coveralls  --no-print-directory
